import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Bell, BookOpenCheck, Check, CircleAlert, Play, Plus, RefreshCw, Siren } from "lucide-react";
import { DataTable, EmptyState, ErrorBanner, KeyValueGrid, LoadingState, Metric, Panel, StatusBadge } from "../components/data/DataDisplay";
import { Page } from "../components/workbench/Workbench";
import type { JsonObject, TableRow } from "../types";
import { acknowledgeNotification, createAlertRule, createIncident, createRunbook, evaluateAlerts, executeRunbook, getOpsSummary, getReliabilitySummary, ingestOpsEvent, listAlertRules, listAlerts, listInbox, listIncidents, listOpsEvents, listRunbooks, updateIncident, type AlertEvent, type AlertRule, type Incident, type OpsEvent, type OpsNotification, type OpsSummary, type ReliabilitySummary, type Runbook } from "../api/opsApi";

type Tab = "command" | "alerts" | "incidents" | "runbooks" | "reliability" | "inbox";
const TABS: Array<{ id: Tab; label: string }> = [{ id: "command", label: "Command Center" }, { id: "alerts", label: "Alerts" }, { id: "incidents", label: "Incidents" }, { id: "runbooks", label: "Runbooks" }, { id: "reliability", label: "Reliability" }, { id: "inbox", label: "Inbox" }];

export function OpsWorkspace() {
  const [tab, setTab] = useState<Tab>("command");
  const [summary, setSummary] = useState<OpsSummary | null>(null); const [events, setEvents] = useState<OpsEvent[]>([]); const [rules, setRules] = useState<AlertRule[]>([]); const [alerts, setAlerts] = useState<AlertEvent[]>([]); const [incidents, setIncidents] = useState<Incident[]>([]); const [runbooks, setRunbooks] = useState<Runbook[]>([]); const [inbox, setInbox] = useState<OpsNotification[]>([]); const [reliability, setReliability] = useState<ReliabilitySummary | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const refresh = useCallback(async () => {
    setLoading(true); setError("");
    try { const values = await Promise.all([getOpsSummary(), listOpsEvents(), listAlertRules(), listAlerts(), listIncidents(), listRunbooks(), listInbox(), getReliabilitySummary()]); setSummary(values[0]); setEvents(values[1]); setRules(values[2]); setAlerts(values[3]); setIncidents(values[4]); setRunbooks(values[5]); setInbox(values[6]); setReliability(values[7]); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Operations workspace could not load"); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const act = async (label: string, task: () => Promise<void>) => { setBusy(label); setError(""); setNotice(""); try { await task(); setNotice(label); } catch (cause) { setError(cause instanceof Error ? cause.message : `${label} failed`); } finally { setBusy(""); } };
  if (loading) return <LoadingState label="Loading operational control plane..." />;
  return <Page title="Operational Control Plane" subtitle="Events, alert evaluation, incidents, governed runbooks, reliability, and team notifications">
    <div className="ops-topbar"><button onClick={() => void refresh()} disabled={!!busy}><RefreshCw size={15} />Refresh</button><button className="primary" onClick={() => void act("Alert rules evaluated", async () => { await evaluateAlerts(); await refresh(); })} disabled={!!busy}><Siren size={15} />Evaluate alerts</button></div>
    <ErrorBanner message={error} />{notice ? <div className="inline-success" role="status">{notice}</div> : null}
    <div className="ops-metrics"><Metric label="Operational events" value={summary?.events || 0} /><Metric label="Open alerts" value={summary?.open_alerts || 0} /><Metric label="Open incidents" value={summary?.open_incidents || 0} /><Metric label="Pending approvals" value={summary?.pending_approvals || 0} /><Metric label="Unread notifications" value={summary?.unread_notifications || 0} /></div>
    <nav className="ops-tabs" aria-label="Operational control views">{TABS.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    {tab === "command" ? <CommandTab summary={summary} events={events} /> : null}
    {tab === "alerts" ? <AlertsTab rules={rules} alerts={alerts} busy={busy} onCreate={(body) => void act("Alert rule created", async () => { await createAlertRule(body); await refresh(); })} onEvent={(body) => void act("Operational event ingested", async () => { await ingestOpsEvent(body); await refresh(); })} /> : null}
    {tab === "incidents" ? <IncidentsTab incidents={incidents} alerts={alerts} busy={busy} onCreate={(body) => void act("Incident opened", async () => { await createIncident(body); await refresh(); })} onResolve={(id) => void act("Incident resolved", async () => { await updateIncident(id, { status: "RESOLVED" }); await refresh(); })} /> : null}
    {tab === "runbooks" ? <RunbooksTab runbooks={runbooks} incidents={incidents} busy={busy} onCreate={(body) => void act("Runbook created", async () => { await createRunbook(body); await refresh(); })} onRun={(id, incidentId) => void act("Runbook execution completed", async () => { await executeRunbook(id, incidentId); await refresh(); })} /> : null}
    {tab === "reliability" ? <ReliabilityTab value={reliability} /> : null}
    {tab === "inbox" ? <InboxTab notes={inbox} busy={busy} onAck={(id) => void act("Notification acknowledged", async () => { await acknowledgeNotification(id); await refresh(); })} /> : null}
  </Page>;
}

function CommandTab({ summary, events }: { summary: OpsSummary | null; events: OpsEvent[] }) {
  const rows: TableRow[] = events.slice(0, 25).map((event) => ({ severity: event.severity, source: event.source, event: event.event_type, title: event.title, status: event.status, occurred: new Date(event.created_at * 1000).toLocaleString() }));
  return <div className="ops-command-layout"><Panel title="Live Operational Feed" action={<Activity size={16} />}><DataTable rows={rows} empty="No operational events yet" /></Panel><Panel title="Current Severity"><KeyValueGrid data={summary?.severity_counts || {}} /><h3>Latest incidents</h3><div className="ops-compact-list">{summary?.latest_incidents.map((item) => <article key={item.id}><span><strong>{item.display_name}</strong><small>{item.owner || "unassigned"}</small></span><StatusBadge value={item.severity} /></article>)}</div>{!summary?.latest_incidents.length ? <div className="empty">No open incidents.</div> : null}</Panel></div>;
}

function AlertsTab({ rules, alerts, busy, onCreate, onEvent }: { rules: AlertRule[]; alerts: AlertEvent[]; busy: string; onCreate: (body: { display_name: string; source?: string; event_type?: string; min_severity: string }) => void; onEvent: (body: { source: string; event_type: string; severity: string; title: string }) => void }) {
  const [ruleName, setRuleName] = useState("Critical reliability events"); const [source, setSource] = useState("decision"); const [severity, setSeverity] = useState("high"); const [eventTitle, setEventTitle] = useState("Asset reliability threshold exceeded");
  return <div className="ops-grid"><Panel title="Alert Rules"><div className="ops-compact-list">{rules.map((rule) => <article key={rule.id}><span><strong>{rule.display_name}</strong><small>{rule.source || "all sources"} · minimum {rule.min_severity}</small></span><StatusBadge value={rule.active ? "active" : "disabled"} /></article>)}</div><div className="form-grid"><label><span>Rule name</span><input aria-label="Alert rule name" value={ruleName} onChange={(event) => setRuleName(event.target.value)} /></label><label><span>Source</span><input aria-label="Alert rule source" value={source} onChange={(event) => setSource(event.target.value)} /></label><label><span>Minimum severity</span><select aria-label="Alert minimum severity" value={severity} onChange={(event) => setSeverity(event.target.value)}><option>medium</option><option>high</option><option>critical</option></select></label></div><button disabled={!ruleName || !!busy} onClick={() => onCreate({ display_name: ruleName, source, min_severity: severity })}><Plus size={14} />Create rule</button></Panel><Panel title="Ingest Test Event"><div className="form-grid"><label><span>Title</span><input aria-label="Operational event title" value={eventTitle} onChange={(event) => setEventTitle(event.target.value)} /></label><label><span>Severity</span><select aria-label="Operational event severity" value={severity} onChange={(event) => setSeverity(event.target.value)}><option>medium</option><option>high</option><option>critical</option></select></label></div><button className="primary" disabled={!eventTitle || !!busy} onClick={() => onEvent({ source, event_type: "reliability.threshold", severity, title: eventTitle })}><CircleAlert size={14} />Ingest event</button><div className="ops-alert-list">{alerts.map((alert) => <article key={alert.id}><StatusBadge value={alert.severity} /><span><strong>{alert.title}</strong><small>{alert.source} · {alert.status}</small></span></article>)}</div>{!alerts.length ? <EmptyState title="No alert events" description="Create a rule, ingest an event, then evaluate alert rules." /> : null}</Panel></div>;
}

function IncidentsTab({ incidents, alerts, busy, onCreate, onResolve }: { incidents: Incident[]; alerts: AlertEvent[]; busy: string; onCreate: (body: { display_name: string; description?: string; severity: string; alert_ids?: string[] }) => void; onResolve: (id: string) => void }) {
  const [name, setName] = useState("Asset reliability investigation"); const [severity, setSeverity] = useState("high");
  return <div className="ops-grid"><Panel title="Open Incident"><div className="form-grid"><label><span>Name</span><input aria-label="Incident name" value={name} onChange={(event) => setName(event.target.value)} /></label><label><span>Severity</span><select aria-label="Incident severity" value={severity} onChange={(event) => setSeverity(event.target.value)}><option>medium</option><option>high</option><option>critical</option></select></label></div><button className="primary" disabled={!name || !!busy} onClick={() => onCreate({ display_name: name, severity, alert_ids: alerts.slice(0, 1).map((item) => item.id) })}><Plus size={14} />Open incident</button></Panel><Panel title="Incident Queue"><div className="ops-incident-list">{incidents.map((item) => <article key={item.id}><header><span><strong>{item.display_name}</strong><small>{item.owner || "unassigned"} · {item.alert_ids.length} alerts</small></span><StatusBadge value={item.severity} /></header><div className="button-row"><StatusBadge value={item.status} /><button disabled={item.status === "RESOLVED" || !!busy} onClick={() => onResolve(item.id)}><Check size={14} />Resolve</button></div></article>)}</div>{!incidents.length ? <EmptyState title="No incidents" description="Promote operational alerts into an owned incident timeline." /> : null}</Panel></div>;
}

function RunbooksTab({ runbooks, incidents, busy, onCreate, onRun }: { runbooks: Runbook[]; incidents: Incident[]; busy: string; onCreate: (body: { display_name: string; description?: string; steps: JsonObject[] }) => void; onRun: (id: string, incidentId?: string) => void }) {
  const [name, setName] = useState("Notify reliability owner"); const [incidentId, setIncidentId] = useState("");
  return <div className="ops-grid"><Panel title="Create Runbook"><label className="stacked-field"><span>Name</span><input aria-label="Runbook name" value={name} onChange={(event) => setName(event.target.value)} /></label><button disabled={!name || !!busy} onClick={() => onCreate({ display_name: name, steps: [{ type: "create_notification", title: "Reliability review required", message: "Review incident evidence and assign an owner.", severity: "high", recipient: "workspace" }] })}><BookOpenCheck size={14} />Create runbook</button></Panel><Panel title="Runbook Library"><label className="stacked-field"><span>Linked incident</span><select aria-label="Runbook incident" value={incidentId} onChange={(event) => setIncidentId(event.target.value)}><option value="">No incident</option>{incidents.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><div className="ops-compact-list">{runbooks.map((item) => <article key={item.id}><span><strong>{item.display_name}</strong><small>{item.steps.length} deterministic steps</small></span><button disabled={!item.enabled || !!busy} onClick={() => onRun(item.id, incidentId)}><Play size={14} />Execute</button></article>)}</div>{!runbooks.length ? <EmptyState title="No runbooks" description="Create deterministic response steps with governed action gates." /> : null}</Panel></div>;
}

function ReliabilityTab({ value }: { value: ReliabilitySummary | null }) { const rows: TableRow[] = (value?.latest_contract_runs || []).map((item) => ({ contract: item.contract_id, status: item.status, asset: item.asset_id, failures: Array.isArray(item.failures) ? item.failures.length : 0 })); return <div className="ops-grid"><Panel title="Reliability Posture" action={<StatusBadge value={value?.status || "unknown"} />}><div className="ops-reliability-metrics"><Metric label="Data contracts" value={value?.data_contracts || 0} /><Metric label="Backfills" value={value?.backfills || 0} /><Metric label="Impact analyses" value={value?.lineage_impact_runs || 0} /></div><KeyValueGrid data={value?.latest_contract_status || {}} /></Panel><Panel title="Latest Data Contract Runs"><DataTable rows={rows} empty="No data contract runs" /></Panel></div>; }
function InboxTab({ notes, busy, onAck }: { notes: OpsNotification[]; busy: string; onAck: (id: string) => void }) { return <Panel title="Operational Inbox" action={<Bell size={16} />}><div className="ops-inbox-list">{notes.map((note) => <article key={note.id}><StatusBadge value={note.severity} /><span><strong>{note.title}</strong><small>{note.message || note.source}</small></span><button disabled={note.status === "ACKED" || !!busy} onClick={() => onAck(note.id)}>{note.status === "ACKED" ? "Acknowledged" : "Acknowledge"}</button></article>)}</div>{!notes.length ? <EmptyState title="Inbox is clear" description="Runbook and incident notifications appear here." /> : null}</Panel>; }
