"""Document which compatibility routes have equivalent typed `/api/v1` coverage.

Tier C requires that compatibility-only routes are retired *once equivalent
typed coverage is documented*. The documenting is the gate; the retirement
follows from it. This produces that document as a measurement rather than a
survey someone wrote by hand and that drifts the moment a route is added.

Three populations matter, and conflating them makes the surface look worse than
it is:

  DUAL      one handler registered at both a plain path and its /api/v1 twin.
            The typed route already covers it, so the plain path is
            compatibility and is retirable once callers have moved.
  V1_ONLY   only under /api/v1. Already typed; nothing owed.
  GENERATED  an unversioned handler eligible for the generated same-handler v1
             adapter in api_v1_compat.py. Both paths use one typed FastAPI route
             contract, so behavior and authorization cannot drift.
  PLAIN_ONLY only outside /api/v1 and explicitly excluded from generation. These
             are browser/auth/health/deployment surfaces, not product APIs.

  python oms/audit_route_coverage.py
  python oms/audit_route_coverage.py --write docs/ROUTE_COVERAGE.md
"""
from __future__ import annotations

import argparse
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, Set

sys.path.insert(0, str(Path(__file__).resolve().parent))
from app.api_v1_compat import (  # noqa: E402
    handler_id,
    iter_assembled_api_routes,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
def handlers() -> tuple[Dict[str, Set[str]], Set[tuple[str, str]], Set[tuple[str, str]]]:
    """Read assembled routes without creating or migrating a database.

    Source parsing cannot resolve ``APIRouter(prefix=...)`` and previously
    misclassified v1-only router modules as plain routes. The assembled FastAPI
    graph is the authoritative contract and generated aliases identify their
    source through an OpenAPI extension.
    """
    os.environ["SKIP_CREATE_ALL"] = "1"
    os.environ["APP_ENV"] = "test"
    os.environ["AUTH_MODE"] = "local"
    from fastapi.routing import APIRoute
    from app.main import app

    registrations: Dict[str, Set[str]] = defaultdict(set)
    generated_sources: Set[tuple[str, str]] = set()
    authoritative_sources: Set[tuple[str, str]] = set()
    for route in iter_assembled_api_routes(app.routes):
        methods = {method.upper() for method in (route.methods or set()) if method not in {"HEAD", "OPTIONS"}}
        source = (route.openapi_extra or {}).get("x-ontologyos-compatibility-source")
        if source:
            continue
        key = handler_id(route)
        registrations[key].update(f"{method} {route.path}" for method in methods)
    for row in app.state.api_v1_compatibility:
        generated_sources.update(
            (row["source_handler"], f"{method} {row['source_path']}")
            for method in row["methods"]
        )
    for row in app.state.api_v1_authoritative:
        authoritative_sources.update(
            (row["source_handler"], f"{method} {row['source_path']}")
            for method in row["methods"]
        )
    return registrations, generated_sources, authoritative_sources


def classify(
    registrations: Dict[str, Set[str]],
    generated_sources: Set[tuple[str, str]],
    authoritative_sources: Set[tuple[str, str]],
):
    dual, v1_only, generated, authoritative, plain_only = {}, {}, {}, {}, {}
    for handler, routes in registrations.items():
        v1 = {r for r in routes if " /api/v1" in r}
        plain = routes - v1
        if v1 and plain:
            dual[handler] = sorted(routes)
        elif v1:
            v1_only[handler] = sorted(routes)
        elif plain and all((handler, route) in generated_sources for route in plain):
            generated[handler] = sorted(routes)
        elif plain and all((handler, route) in authoritative_sources for route in plain):
            authoritative[handler] = sorted(routes)
        elif plain:
            plain_only[handler] = sorted(routes)
    return dual, v1_only, generated, authoritative, plain_only


def render(dual, v1_only, generated, authoritative, plain_only) -> str:
    total = len(dual) + len(v1_only) + len(generated) + len(authoritative) + len(plain_only)
    lines = [
        "# Route Coverage: Typed `/api/v1` Against Compatibility Paths",
        "",
        "Generated by `python oms/audit_route_coverage.py`. Tier C retires",
        "compatibility-only routes *once equivalent typed coverage is documented*, so this",
        "is the document that gate depends on. It is produced from the source rather than",
        "maintained by hand, because a hand-maintained list of 700-odd routes is wrong the",
        "day after it is written.",
        "",
        "## Summary",
        "",
        f"| Population | Handlers | Meaning |",
        f"| --- | --- | --- |",
        f"| Dual-registered | {len(dual)} | Typed route exists; the plain path is compatibility and is retirable once callers move |",
        f"| Generated same-handler aliases | {len(generated)} | The assembly-time adapter adds typed `/api/v1` paths backed by the exact legacy endpoint and dependencies |",
        f"| Explicit v1 successors | {len(authoritative)} | An explicit v1 route owns the same method/shape; generation correctly defers to it |",
        f"| `/api/v1` only | {len(v1_only)} | Already typed; nothing owed |",
        f"| Deliberately unversioned | {len(plain_only)} | Browser, authentication, probe, documentation, or deployment surfaces excluded from product API versioning |",
        f"| **Total handlers** | **{total}** | |",
        "",
        "Generated aliases are real FastAPI `APIRoute` contracts, not HTTP forwarding:",
        "request validation, response models, dependencies, status codes, and endpoint",
        "identity are cloned while explicit v1 route-shape collisions remain authoritative.",
        "`GET /api/v1/compatibility/manifest` exposes the runtime inventory.",
        "",
        "## Dual-registered handlers, retirable once callers move",
        "",
    ]
    if dual:
        for handler in sorted(dual):
            routes = dual[handler]
            typed = [r for r in routes if " /api/v1" in r]
            compat = [r for r in routes if " /api/v1" not in r]
            lines.append(f"- `{handler}`")
            for route in typed:
                lines.append(f"  - typed: `{route}`")
            for route in compat:
                lines.append(f"  - compatibility: `{route}`")
    else:
        lines.append("_None._")
    lines += [
        "",
        "## Generated same-handler compatibility aliases",
        "",
        f"{len(generated)} handlers receive additive typed aliases from",
        "`oms/app/api_v1_compat.py` after application assembly. The source path remains",
        "available during migration and an explicit v1 implementation always wins a",
        "method/route-shape collision.",
        "",
    ]
    for handler in sorted(generated):
        lines.append(f"- `{handler}`: " + ", ".join(f"`{route}`" for route in generated[handler]))
    lines += [
        "",
        "## Plain handlers covered by explicit v1 successors",
        "",
        f"{len(authoritative)} handlers are not cloned because an explicit v1 route already",
        "owns the same method and normalized route shape.",
        "",
        "",
        "## Deliberately unversioned handlers",
        "",
        f"{len(plain_only)} handlers remain outside `/api/v1` because the compatibility",
        "policy excludes browser pages, authentication callbacks, health probes, metrics,",
        "and framework documentation from the versioned product API.",
        "",
        "## What this measurement does not cover",
        "",
        "The inventory reads the fully assembled FastAPI route graph with database DDL",
        "disabled. This resolves router prefixes and multiline declarations that source",
        "parsing cannot. It does not exercise endpoint behavior; behavioral parity, project",
        "authorization, OpenAPI shape, collisions, and idempotent installation are covered by",
        "`oms/test_api_v1_compatibility.py`.",
        "",
        "The audit also proves only that a typed path is *registered*, not that it is",
        "behaviourally equivalent to its compatibility twin. Dual registration on one",
        "handler is strong evidence -- the same function serves both -- but retirement",
        "should still confirm that no caller depends on response-shape differences the",
        "typed route may impose.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", default="")
    args = parser.parse_args()

    registrations, generated_sources, authoritative_sources = handlers()
    dual, v1_only, generated, authoritative, plain_only = classify(
        registrations, generated_sources, authoritative_sources,
    )
    total = len(dual) + len(v1_only) + len(generated) + len(authoritative) + len(plain_only)
    print("Route coverage audit\n")
    print(f"  dual-registered (retirable)  {len(dual)}")
    print(f"  generated typed aliases      {len(generated)}")
    print(f"  explicit v1 successors       {len(authoritative)}")
    print(f"  /api/v1 only                 {len(v1_only)}")
    print(f"  deliberately unversioned     {len(plain_only)}")
    print(f"  total handlers               {total}")
    if dual:
        print("\n  Dual-registered handlers:")
        for handler in sorted(dual)[:20]:
            print(f"    {handler}")
        if len(dual) > 20:
            print(f"    ... and {len(dual) - 20} more")

    if args.write:
        destination = REPO_ROOT / args.write
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render(dual, v1_only, generated, authoritative, plain_only), encoding="utf-8")
        print(f"\nWrote {args.write}")
    return 0


if __name__ == "__main__":
    from enforcement_runs import recording  # noqa: E402
    sys.exit(recording("audit_route_coverage", main))