"""Every shared UI primitive, who uses it, and a reference that cannot go stale.

Seven workspaces hand-rolled their empty states while `EmptyState` sat in the
shared components file. That is not laziness; it is what happens when the
primitives cannot be found. `src/components` is four files exporting twenty-odd
components, and nothing listed them.

`WorkspaceHeader` was the sharpest case. It read as *the* header every workspace
should use, one workspace used it, two wrote the same markup by hand -- and it
hardcodes the word "Batch" and highlights a tab called "Graph". It was the
pipeline builder's header wearing a general name, which is worse than no
primitive at all: a reader who opens it learns not to trust the layer. It now
lives in `PipelineBuilder.tsx` as `PipelineHeader`.

`docs/UI_PRIMITIVES.md` is generated from the source rather than written beside
it, because a hand-maintained component list is a claim that decays the first
time someone adds a component. The gate regenerates and compares:

  - *Gated:* the checked-in reference disagreeing with the source. Regenerating
    is one command; a stale list is the thing this replaces.
  - *Gated:* an exported primitive that no file imports **and** no declaration
    explains. The first version of this rule simply deleted the one it found,
    and the suite caught it: `DebugJson` is imported by nothing and is the only
    place raw JSON is rendered, which `test_ui_alignment_acceptance.py` asserts
    as a design guarantee -- raw JSON must stay isolated to collapsed developer
    evidence. Unimported is not dead. So an unused export may stay if it says
    why, and a reader who finds it learns what it is holding.
  - *Reported:* adoption per primitive, so a primitive used once is visible
    rather than presumed general.

Adoption is not gated upward. Twelve of twenty-two workspaces using `Page` is a
fact worth seeing, not a rule to enforce; some screens legitimately do not want
the wrapper, and a gate that demanded uniformity would be enforcing taste.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))

FRONTEND_SRC = REPO_ROOT / "frontend" / "src"
COMPONENTS = FRONTEND_SRC / "components"
REFERENCE = REPO_ROOT / "docs" / "UI_PRIMITIVES.md"

_EXPORT = re.compile(r"^export function ([A-Z][A-Za-z0-9]*)", re.M)

# Exported, imported by nothing, and deliberately kept. Each says what it holds,
# because "nobody imports it" and "nothing needs it" are different claims and
# this repository confused them once already.
DECLARED_UNUSED = {
    "DebugJson": ("the only component that renders raw JSON, and it renders it inside "
                  "DeveloperEvidence. test_ui_alignment_acceptance.py asserts that "
                  "isolation; deleting it removed the guarantee's only expression"),
}


def scan() -> Dict[str, Dict[str, Any]]:
    """Each exported primitive: where it lives, and which files import it."""
    primitives: Dict[str, Dict[str, Any]] = {}
    for path in sorted(COMPONENTS.rglob("*.tsx")):
        module = str(path.relative_to(FRONTEND_SRC)).replace("\\", "/")
        for name in _EXPORT.findall(path.read_text(encoding="utf-8")):
            primitives[name] = {"module": module, "users": []}

    for path in sorted(FRONTEND_SRC.rglob("*.tsx")):
        if "components/" in str(path).replace("\\", "/"):
            continue
        text = path.read_text(encoding="utf-8")
        label = str(path.relative_to(FRONTEND_SRC)).replace("\\", "/")
        for block in re.findall(r"import \{([^}]*)\} from \"[^\"]*components/[^\"]*\";", text):
            for token in (t.strip() for t in block.split(",")):
                if token in primitives:
                    primitives[token]["users"].append(label)
    for entry in primitives.values():
        entry["users"] = sorted(set(entry["users"]))
    return primitives


def render(primitives: Dict[str, Dict[str, Any]]) -> str:
    lines = [
        "# UI primitives",
        "",
        "Generated by `oms/audit_ui_primitives.py`. Do not edit by hand — the gate",
        "regenerates this and fails if it disagrees with the source, because a",
        "hand-maintained component list is a claim that decays the first time",
        "someone adds a component.",
        "",
        "Seven workspaces hand-rolled their empty states while `EmptyState` sat in",
        "`components/data/DataDisplay.tsx`. Nothing listed it. This is that list.",
        "",
        "| Primitive | Defined in | Used by |",
        "| --- | --- | --- |",
    ]
    for name, entry in sorted(primitives.items(), key=lambda i: (-len(i[1]["users"]), i[0])):
        users = entry["users"]
        where = ", ".join(u.replace("workspaces/", "").replace(".tsx", "") for u in users[:4])
        if len(users) > 4:
            where += f", and {len(users) - 4} more"
        lines.append(f"| `{name}` | `{entry['module']}` | **{len(users)}** — {where or '—'} |")
    lines.append("")
    return "\n".join(lines)


def compare(primitives: Dict[str, Dict[str, Any]]) -> Tuple[bool, List[str], List[str]]:
    failures: List[str] = []
    notes: List[str] = []

    orphans = sorted(name for name, entry in primitives.items()
                     if not entry["users"] and name not in DECLARED_UNUSED)
    if orphans:
        failures.append(
            f"{len(orphans)} exported primitive(s) that no file imports and nothing explains: "
            f"{', '.join(orphans)}. Delete it, use it, or say in DECLARED_UNUSED what it "
            f"holds -- unimported is not the same as dead.")
    for name in sorted(DECLARED_UNUSED):
        if name in primitives and primitives[name]["users"]:
            notes.append(f"{name} is declared unused and is now imported by "
                         f"{len(primitives[name]['users'])} file(s) -- remove the declaration")

    if not REFERENCE.exists():
        failures.append(f"{REFERENCE.relative_to(REPO_ROOT)} is missing; regenerate it with "
                        f"--write")
    elif REFERENCE.read_text(encoding="utf-8") != render(primitives):
        failures.append(
            f"{REFERENCE.relative_to(REPO_ROOT)} disagrees with the source. Regenerate it: "
            f"python oms/audit_ui_primitives.py --write")

    single = sorted(name for name, entry in primitives.items() if len(entry["users"]) == 1)
    if single:
        notes.append(f"{len(single)} primitive(s) used by exactly one file: "
                     f"{', '.join(single[:6])}{'…' if len(single) > 6 else ''}")
    return not failures, failures, notes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate the reference")
    args = parser.parse_args()

    if not COMPONENTS.exists():
        print(f"No components at {COMPONENTS}")
        return 1

    primitives = scan()
    adopted = sum(1 for entry in primitives.values() if entry["users"])
    print(f"{len(primitives)} exported primitive(s), {adopted} imported somewhere\n")
    for name, entry in sorted(primitives.items(), key=lambda i: -len(i[1]["users"]))[:10]:
        print(f"  {len(entry['users']):>3} users  {name}")

    if args.write:
        REFERENCE.write_text(render(primitives), encoding="utf-8")
        print(f"\nWrote {REFERENCE.relative_to(REPO_ROOT)} ({len(primitives)} primitives).")
        return 0

    ok, failures, notes = compare(primitives)
    for note in notes:
        print(f"\n  {note}")
    if failures:
        print(f"\nFAIL -- {len(failures)}:")
        for failure in failures:
            print(f"  {failure}")
        return 1
    print(f"\nEvery primitive is imported somewhere, and the reference matches the source.")
    return 0


if __name__ == "__main__":
    from enforcement_runs import recording

    raise SystemExit(recording("audit_ui_primitives", main))
