"""Document which compatibility routes have equivalent typed `/api/v1` coverage.

Tier C requires that compatibility-only routes are retired *once equivalent
typed coverage is documented*. The documenting is the gate; the retirement
follows from it. This produces that document as a measurement rather than a
survey someone wrote by hand and that drifts the moment a route is added.

Three populations matter, and conflating them makes the surface look worse than
it is:

  DUAL      one handler registered at both a plain path and its /api/v1 twin.
            The typed route already covers it, so the plain path is
            compatibility and is retirable once callers have moved.
  V1_ONLY   only under /api/v1. Already typed; nothing owed.
  PLAIN_ONLY only outside /api/v1. These are not compatibility routes with a
            typed successor -- they are surface with no typed equivalent yet, so
            retiring them would remove capability rather than duplication.

  python oms/audit_route_coverage.py
  python oms/audit_route_coverage.py --write docs/ROUTE_COVERAGE.md
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Set

REPO_ROOT = Path(__file__).resolve().parent.parent
APP = REPO_ROOT / "oms" / "app"

DECORATOR = re.compile(
    r'^@(?:\w+)\.(get|post|put|patch|delete)\(\s*["\']([^"\']+)["\']', re.MULTILINE
)
DEF_LINE = re.compile(r"^(?:async\s+)?def\s+(\w+)", re.MULTILINE)


def handlers() -> Dict[str, Set[str]]:
    """Map handler identity to the set of METHOD PATH it is registered at.

    Decorators stack directly above the function, so the routes belonging to one
    handler are the run of consecutive decorator lines preceding its def.
    """
    registrations: Dict[str, Set[str]] = defaultdict(set)
    for source_path in sorted(APP.glob("*.py")):
        lines = source_path.read_text(encoding="utf-8", errors="ignore").split("\n")
        pending: List[str] = []
        for line in lines:
            decorator = DECORATOR.match(line)
            if decorator:
                pending.append(f"{decorator.group(1).upper()} {decorator.group(2)}")
                continue
            definition = DEF_LINE.match(line)
            if definition and pending:
                key = f"{source_path.name}:{definition.group(1)}"
                registrations[key].update(pending)
                pending = []
            elif definition:
                pending = []
            elif line.strip() and not line.startswith((" ", ")", "@", "#")):
                # Any other top-level statement breaks a decorator run.
                pending = []
    return registrations


def classify(registrations: Dict[str, Set[str]]):
    dual, v1_only, plain_only = {}, {}, {}
    for handler, routes in registrations.items():
        v1 = {r for r in routes if " /api/v1" in r}
        plain = routes - v1
        if v1 and plain:
            dual[handler] = sorted(routes)
        elif v1:
            v1_only[handler] = sorted(routes)
        elif plain:
            plain_only[handler] = sorted(routes)
    return dual, v1_only, plain_only


def render(dual, v1_only, plain_only) -> str:
    total = len(dual) + len(v1_only) + len(plain_only)
    lines = [
        "# Route Coverage: Typed `/api/v1` Against Compatibility Paths",
        "",
        "Generated by `python oms/audit_route_coverage.py`. Tier C retires",
        "compatibility-only routes *once equivalent typed coverage is documented*, so this",
        "is the document that gate depends on. It is produced from the source rather than",
        "maintained by hand, because a hand-maintained list of 700-odd routes is wrong the",
        "day after it is written.",
        "",
        "## Summary",
        "",
        f"| Population | Handlers | Meaning |",
        f"| --- | --- | --- |",
        f"| Dual-registered | {len(dual)} | Typed route exists; the plain path is compatibility and is retirable once callers move |",
        f"| `/api/v1` only | {len(v1_only)} | Already typed; nothing owed |",
        f"| Plain only | {len(plain_only)} | No typed equivalent yet; retiring these removes capability, not duplication |",
        f"| **Total handlers** | **{total}** | |",
        "",
        "The distinction matters. A raw count of non-`/api/v1` paths reads as a large",
        "compatibility surface, but most of it has no typed twin to be redundant against.",
        "Only the dual-registered handlers are retirable on the strength of typed coverage;",
        "the plain-only ones need a typed route built first, which is work rather than",
        "cleanup.",
        "",
        "## Dual-registered handlers, retirable once callers move",
        "",
    ]
    if dual:
        for handler in sorted(dual):
            routes = dual[handler]
            typed = [r for r in routes if " /api/v1" in r]
            compat = [r for r in routes if " /api/v1" not in r]
            lines.append(f"- `{handler}`")
            for route in typed:
                lines.append(f"  - typed: `{route}`")
            for route in compat:
                lines.append(f"  - compatibility: `{route}`")
    else:
        lines.append("_None._")
    lines += [
        "",
        "## Plain-only handlers, no typed equivalent",
        "",
        f"{len(plain_only)} handlers are registered outside `/api/v1` with no typed twin.",
        "These are not retirement candidates under the Tier C condition: the condition",
        "presumes equivalent typed coverage, and there is none to point at. Listing them",
        "here keeps the gap visible rather than letting the summary imply the surface is",
        "already typed.",
        "",
        "## What this measurement does not cover",
        "",
        "The parser reads a route path only when it appears on the decorator line itself.",
        "Five of 1,041 decorators in `oms/app` span multiple lines and are invisible to it,",
        "so the counts are accurate to roughly half a percent. That is stated rather than",
        "rounded away because a coverage document whose error bar is unknown cannot be used",
        "to justify deleting a route.",
        "",
        "The audit also proves only that a typed path is *registered*, not that it is",
        "behaviourally equivalent to its compatibility twin. Dual registration on one",
        "handler is strong evidence -- the same function serves both -- but retirement",
        "should still confirm that no caller depends on response-shape differences the",
        "typed route may impose.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", default="")
    args = parser.parse_args()

    dual, v1_only, plain_only = classify(handlers())
    total = len(dual) + len(v1_only) + len(plain_only)
    print("Route coverage audit\n")
    print(f"  dual-registered (retirable)  {len(dual)}")
    print(f"  /api/v1 only                 {len(v1_only)}")
    print(f"  plain only (no typed twin)   {len(plain_only)}")
    print(f"  total handlers               {total}")
    if dual:
        print("\n  Dual-registered handlers:")
        for handler in sorted(dual)[:20]:
            print(f"    {handler}")
        if len(dual) > 20:
            print(f"    ... and {len(dual) - 20} more")

    if args.write:
        destination = REPO_ROOT / args.write
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render(dual, v1_only, plain_only), encoding="utf-8")
        print(f"\nWrote {args.write}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
